[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
GeothermalWells = "9e50befb-bb92-4f5a-8f9f-381c571c0866"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
OrdinaryDiffEqStabilizedRK = "358294b1-0aab-51c3-aafe-ad5ab194a2ad"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
